WATCHLIST_MIN_MCAP: "1000"
WATCHLIST_MAX_MCAP: "150000"
WATCHLIST_MIN_VOL_5M: "10"
WATCHLIST_MIN_VOL_1H: "1000"
WATCHLIST_MIN_BUYS_1H: "2"
WATCHLIST_MIN_LIQ: "1000"

PUBLIC_MIN_MCAP: "4000"
PUBLIC_MAX_MCAP: "150000"
PUBLIC_MIN_VOL_5M: "50"
PUBLIC_MIN_VOL_1H: "6000"
PUBLIC_MIN_BUYS_1H: "8"
PUBLIC_MIN_LIQ: "3000"
PUBLIC_MIN_BUY_SELL_RATIO: "0.95"
PUBLIC_MAX_RUG_DNA: "65"
